server:
  port: 0

spring:
  application:
    name: benchmark
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false

    hikari:
      jdbc-url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 10
  zipkin:
    enabled: false


decorator:
  datasource:
    enabled: false
    p6spy:
      enable-logging: false
    datasource-proxy:
      query:
        enable-logging: false
      slow-query:
        enable-logging: false
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: TRACE
