server:
  port: 0

spring:
  sleuth:
    enabled: false
    sampler:
      percentage: 1
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    initialize: false

    hikari:
      jdbc-url: jdbc:h2:mem:test-${random.int};DB_CLOSE_DELAY=-1
      username: sa
      password:
      maximum-pool-size: 10
logging:
  level:
    ROOT: info

decorator:
  datasource:
    enabled: false
